CREATE TABLE Notes (
	Id INT NOT NULL PRIMARY KEY IDENTITY,
	Text NVARCHAR(MAX) NOT NULL
);

CREATE TABLE Tags (
	Name NVARCHAR(20) NOT NULL PRIMARY KEY
);

CREATE TABLE NoteTags (
	NoteId INT NOT NULL FOREIGN KEY REFERENCES Notes (Id) ON DELETE CASCADE,
	Name NVARCHAR(20) NOT NULL FOREIGN KEY REFERENCES Tags (Name) ON DELETE CASCADE
);

ALTER TABLE NoteTags ADD
    PRIMARY KEY (NoteId, Name);

INSERT INTO Notes (Text) VALUES
    ('asdf');
    
INSERT INTO Tags (Name) VALUES
    ('C#'),
    ('SQL');

SELECT * FROM Notes;

INSERT INTO NoteTags (NoteId, Name) VALUES
    (1, 'SQL');
